In [1]:
# Importing the Keras libraries and packages
#import pretrainded models
from keras.applications.vgg16 import VGG16
from tensorflow.keras.applications.resnet50 import ResNet50
from keras.applications.vgg19 import VGG19
#import packages
from keras.models import Model
from keras.preprocessing import image
from tensorflow.keras.layers import Input, Lambda ,Dense ,Flatten ,Dropout
import numpy as np
import tensorflow as tf
import pandas as pd
import keras
import matplotlib.pyplot as plt
%matplotlib inline
import os
import cv2
from tensorflow.keras.preprocessing.image import load_img,img_to_array
from sklearn.model_selection import train_test_split
from keras.utils.np_utils import to_categorical

In [2]:
def load_image_data(directory):
    
    images = []
    labels = []
    for label in sorted(os.listdir(directory)):
        for image in os.listdir(directory + "/" + label ):
            img = cv2.resize(cv2.imread(directory + "/" + label+ "/" +image), (224, 224))
            images.append(img)
            labels.append(label)
    images = np.array(images)
    labels = np.array(labels)
    return (images,labels)

In [3]:
x_test,y_test=load_image_data(r'C:\Users\pc\Downloads\hand_recog\test')

In [4]:
len(x_test)

86

In [5]:
x_test=x_test.astype(float)/255.0

In [6]:
x_test1= np.expand_dims(x_test, axis = 1)

In [7]:
x_test1[0].shape

(1, 224, 224, 3)

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_test_cat = le.fit_transform(y_test)
y_test_cat = to_categorical(y_test_cat)
y_test_cat[0]

array([1., 0., 0., 0., 0.], dtype=float32)

In [9]:
model= keras.models.load_model(r"C:\Users\pc\Downloads\hand_recog\model")

In [10]:
import cv2
from cvzone.HandTrackingModule import HandDetector
import numpy as np
import math
import time
import os

In [11]:
labels=list(np.unique(y_test))

In [ ]:
cap = cv2.VideoCapture(0)
detector = HandDetector(maxHands=1)

 
offset = 20
imgSize = 224
  
labels = ['Hello', 'Open', 'Please', 'Telephone', 'Think']
 
while True:
    success, img = cap.read()
    imgOutput = img.copy()
    hands, img = detector.findHands(img)
    if hands:
        hand = hands[0]
        x, y, w, h = hand['bbox']
 
        imgWhite = np.ones((imgSize, imgSize, 3), np.uint8) * 255
        imgCrop = img[y - offset:y + h + offset, x - offset:x + w + offset]
 
        imgCropShape = imgCrop.shape
 
        aspectRatio = h / w
 
        if aspectRatio > 1:
            k = imgSize / h
            wCal = math.ceil(k * w)
            imgResize = cv2.resize(imgCrop, (wCal, imgSize))
            imgResizeShape = imgResize.shape
            wGap = math.ceil((imgSize - wCal) / 2)
            imgWhite[:, wGap:wCal + wGap] = imgResize
            imgWhite1=imgWhite.reshape(1,224,224,3)
            prediction= model.predict(imgWhite1)
            index=np.argmax(prediction)
            print(prediction, index)
 
        else:
            k = imgSize / w
            hCal = math.ceil(k * h)
            imgResize = cv2.resize(imgCrop, (imgSize, hCal))
            imgResizeShape = imgResize.shape
            hGap = math.ceil((imgSize - hCal) / 2)
            imgWhite[hGap:hCal + hGap, :] = imgResize
            imgWhite1=imgWhite.reshape(1,224,224,3)
            prediction= model.predict(imgWhite1)
            index=np.argmax(prediction)
            print(prediction, index)
 
 
        cv2.rectangle(imgOutput, (x - offset, y - offset-50),
                      (x - offset+90, y - offset-50+50), (255, 0, 255), cv2.FILLED)
        cv2.putText(imgOutput, labels[index], (x, y -26), cv2.FONT_HERSHEY_COMPLEX, 1.7, (255, 255, 255), 2)
        cv2.rectangle(imgOutput, (x-offset, y-offset),
                      (x + w+offset, y + h+offset), (255, 0, 255), 4)
 
 
        cv2.imshow("ImageCrop", imgCrop)
        cv2.imshow("ImageWhite", imgWhite)
 
    cv2.imshow("Image", imgOutput)
    cv2.waitKey(1)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        cap.release()
        cv2.destroyAllWindows()

1/1 [==============================] - 0s 442ms/step
[[1.6198216e-13 8.6216110e-34 0.0000000e+00 1.0000000e+00 1.8591077e-18]] 3
1/1 [==============================] - 0s 303ms/step
[[2.4112389e-18 2.4432308e-24 0.0000000e+00 1.0000000e+00 2.8651610e-21]] 3
1/1 [==============================] - 0s 306ms/step
[[7.8965246e-20 6.7266981e-33 0.0000000e+00 1.0000000e+00 1.2333456e-18]] 3
1/1 [==============================] - 0s 285ms/step
[[4.8607375e-02 1.3040892e-17 0.0000000e+00 9.5139265e-01 1.1530073e-33]] 3
1/1 [==============================] - 0s 259ms/step
[[9.9999821e-01 6.9963918e-15 0.0000000e+00 1.7765776e-06 0.0000000e+00]] 0
1/1 [==============================] - 0s 268ms/step
[[1.0000000e+00 5.1558287e-25 0.0000000e+00 4.4375711e-10 0.0000000e+00]] 0
1/1 [==============================] - 0s 273ms/step
[[1.0000000e+00 7.8089491e-24 0.0000000e+00 2.4611913e-09 0.0000000e+00]] 0
1/1 [==============================] - 0s 262ms/step
[[1.0000000e+00 1.3193606e-19 0.0000000e+00 

1/1 [==============================] - 0s 307ms/step
[[0.0000000e+00 8.9273126e-19 0.0000000e+00 5.5285346e-30 1.0000000e+00]] 4
1/1 [==============================] - 0s 303ms/step
[[0.0000000e+00 5.2460572e-18 0.0000000e+00 1.8215074e-27 1.0000000e+00]] 4
1/1 [==============================] - 0s 295ms/step
[[0.0000000e+00 2.9733382e-19 0.0000000e+00 2.6754998e-27 1.0000000e+00]] 4
1/1 [==============================] - 0s 289ms/step
[[0.0000000e+00 5.4997731e-25 0.0000000e+00 3.2988653e-34 1.0000000e+00]] 4
1/1 [==============================] - 0s 289ms/step
[[0.000000e+00 1.361874e-28 0.000000e+00 4.620049e-33 1.000000e+00]] 4
1/1 [==============================] - 0s 288ms/step
[[0.0000000e+00 1.8895751e-16 0.0000000e+00 1.8723821e-32 1.0000000e+00]] 4
1/1 [==============================] - 0s 294ms/step
[[0.0000000e+00 1.6233179e-19 0.0000000e+00 2.7445568e-32 1.0000000e+00]] 4
1/1 [==============================] - 0s 300ms/step
[[0.0000000e+00 6.3140513e-22 0.0000000e+00 3.216

1/1 [==============================] - 0s 267ms/step
[[0.0000000e+00 3.9135865e-12 9.9941111e-01 1.0149329e-37 5.8893848e-04]] 2
1/1 [==============================] - 0s 267ms/step
[[0.0000000e+00 1.0310727e-17 3.3025541e-03 0.0000000e+00 9.9669743e-01]] 4
1/1 [==============================] - 0s 272ms/step
[[0.0000000e+00 1.2501913e-15 5.8452410e-01 0.0000000e+00 4.1547588e-01]] 2
1/1 [==============================] - 0s 261ms/step
[[0.0000000e+00 3.6546618e-16 9.0337835e-02 1.8292658e-38 9.0966219e-01]] 4
1/1 [==============================] - 0s 273ms/step
[[0.0000000e+00 1.0334652e-21 9.9994242e-01 0.0000000e+00 5.7579677e-05]] 2
1/1 [==============================] - 0s 267ms/step
[[0.0000000e+00 1.2382354e-18 9.9995518e-01 0.0000000e+00 4.4877383e-05]] 2
1/1 [==============================] - 0s 265ms/step
[[0.0000000e+00 7.1674817e-13 9.9919766e-01 0.0000000e+00 8.0238678e-04]] 2
1/1 [==============================] - 0s 269ms/step
[[0.0000000e+00 1.3579950e-16 9.6297789e-01 

1/1 [==============================] - 0s 286ms/step
[[0.0000000e+00 3.9409172e-24 1.3543055e-20 4.7157541e-34 1.0000000e+00]] 4
1/1 [==============================] - 0s 280ms/step
[[0.0000000e+00 3.8224868e-21 2.8252585e-17 3.9415811e-30 1.0000000e+00]] 4
1/1 [==============================] - 0s 287ms/step
[[4.9545531e-35 3.0464736e-05 7.9866190e-04 2.9674249e-11 9.9917090e-01]] 4
1/1 [==============================] - 0s 284ms/step
[[0.0000000e+00 8.5790634e-33 1.6403781e-22 3.3401408e-22 1.0000000e+00]] 4
1/1 [==============================] - 0s 283ms/step
[[0.0000000e+00 5.5816149e-31 3.6780712e-20 9.1963734e-26 1.0000000e+00]] 4
1/1 [==============================] - 0s 283ms/step
[[0.0000000e+00 7.0715272e-32 7.8075967e-27 1.5184992e-34 1.0000000e+00]] 4
1/1 [==============================] - 0s 290ms/step
[[4.4566734e-38 4.3615706e-12 9.9881424e-07 3.6708965e-17 9.9999905e-01]] 4
1/1 [==============================] - 0s 266ms/step
[[0.000000e+00 8.116108e-25 6.383252e-02 6.6

1/1 [==============================] - 0s 266ms/step
[[3.4612579e-18 1.8268453e-06 2.2559374e-26 9.9998784e-01 1.0325571e-05]] 3
1/1 [==============================] - 0s 283ms/step
[[4.1380146e-29 1.3136999e-20 1.1104531e-35 1.0000000e+00 3.4907949e-08]] 3
1/1 [==============================] - 0s 273ms/step
[[2.7025979e-29 4.2953323e-19 4.3068153e-35 1.0000000e+00 9.3091444e-11]] 3
1/1 [==============================] - 0s 272ms/step
[[2.04335016e-25 1.47032320e-16 4.10970366e-34 1.00000000e+00
  1.43114505e-11]] 3
1/1 [==============================] - 0s 276ms/step
[[4.8576399e-19 1.5520020e-07 6.4389205e-24 9.9999976e-01 5.9971939e-08]] 3
1/1 [==============================] - 0s 282ms/step
[[2.1042717e-36 2.6087545e-07 1.0389027e-24 1.7628605e-12 9.9999976e-01]] 4
1/1 [==============================] - 0s 276ms/step
[[0.0000000e+00 3.4487530e-18 2.9466086e-36 1.5070679e-26 1.0000000e+00]] 4
1/1 [==============================] - 0s 300ms/step
[[0.0000000e+00 3.6447765e-11 1.68871

1/1 [==============================] - 0s 263ms/step
[[0.0000000e+00 9.7786730e-32 0.0000000e+00 2.2636924e-23 1.0000000e+00]] 4
1/1 [==============================] - 0s 307ms/step
[[0.0000000e+00 1.8356944e-32 0.0000000e+00 6.0810870e-04 9.9939191e-01]] 4
1/1 [==============================] - 0s 285ms/step
[[0.0000000e+00 2.3515828e-35 0.0000000e+00 2.3089887e-03 9.9769104e-01]] 4
1/1 [==============================] - 0s 264ms/step
[[0.0000000e+00 4.3845093e-36 0.0000000e+00 1.5613290e-08 1.0000000e+00]] 4
1/1 [==============================] - 0s 267ms/step
[[0.00000000e+00 2.00270886e-37 0.00000000e+00 8.95365894e-01
  1.04634106e-01]] 3
1/1 [==============================] - 0s 275ms/step
[[0.000000e+00 0.000000e+00 0.000000e+00 6.596776e-07 9.999993e-01]] 4
1/1 [==============================] - 0s 291ms/step
[[0.0000000e+00 5.8957861e-36 0.0000000e+00 9.9100983e-01 8.9901518e-03]] 3
1/1 [==============================] - 0s 263ms/step
[[0.        0.        0.        0.9879018 

In [ ]:
q